version: 2

build:
  os: ubuntu-22.04
  apt_packages:
    - pandoc

  tools:
    python: '3.8'

sphinx:
  fail_on_warning: true
  configuration: docs/conf.py

python:
   install:
     - requirements: docs/requirements.txt
